version: "3"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
      - '1234:1234'
    links:
      - postgres
    volumes:
      - app-sync:/app:nocopy
      - ./db:/app/db
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app-sync:
    external: true
